### ISSUE TITLE
cannot VACUUM from within a transaction

### ISSUE THREAD

**Issue by wen-fei** [MedevaKnowledgeSystems/pymedtermino#2]
in python3.6 , the following messages will show:
`Traceback (most recent call last):
  File ".\scripts\import_icd10.py", line 323, in <module>
    do_sql(u"""VACUUM;""")
  File ".\scripts\import_icd10.py", line 85, in do_sql
    db_cursor.execute(sql, *args)
sqlite3.OperationalError: cannot VACUUM from within a transaction
`

**Comment by wen-fei** [comment]
fixed:
in import_icd10.py line 77
`if sys.version[0] == "2":
    db_cursor = db.cursor()
else:
    db.isolation_level = None
    db_cursor = db.cursor()
`
